config/routes.rb
Reminderize::Application.routes.draw do
  resources :reminders

  match "mob/process" => "mob#processed"

  resources :task_lists

  devise_for :users

  resources :roles

  resources :task_groups

  resources :tasks
  root :to => "tasks#index"

end

app/models/task_group.rb
class TaskGroup < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :role

  validates :task_id, :presence => true
  validates :user_id, :presence => true
  validates :role_id, :presence => true
end

app/controllers/task_groups_controller.rb
class TaskGroupsController < ApplicationController
  # GET /task_groups
  # GET /task_groups.xml
  def index
    @task_groups = TaskGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @task_groups }
    end
  end

  # GET /task_groups/1
  # GET /task_groups/1.xml
  def show
    @task_group = TaskGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task_group }
    end
  end

  # GET /task_groups/new
  # GET /task_groups/new.xml
  def new
    @task_group = TaskGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task_group }
    end
  end

  # GET /task_groups/1/edit
  def edit
    @task_group = TaskGroup.find(params[:id])
  end

  # POST /task_groups
  # POST /task_groups.xml
  def create
    @task_group = TaskGroup.new(params[:task_group])

    respond_to do |format|
      if @task_group.save
        format.html { redirect_to(@task_group, :notice => 'Task group was successfully created.') }
        format.xml  { render :xml => @task_group, :status => :created, :location => @task_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /task_groups/1
  # PUT /task_groups/1.xml
  def update
    @task_group = TaskGroup.find(params[:id])

    respond_to do |format|
      if @task_group.update_attributes(params[:task_group])
        format.html { redirect_to(@task_group, :notice => 'Task group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /task_groups/1
  # DELETE /task_groups/1.xml
  def destroy
    @task_group = TaskGroup.find(params[:id])
    @task_group.destroy

    respond_to do |format|
      format.html { redirect_to(task_groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/task_groups_helper.rb
module TaskGroupsHelper
end

app/views/task_groups/_form.html.erb
<%= form_for(@task_group) do |f| %>
  <% if @task_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_group.errors.count, "error") %> prohibited this task_group from being saved:</h2>

      <ul>
      <% @task_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.text_field :role_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_groups/edit.html.erb
<h1>Editing task_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_group %> |
<%= link_to 'Back', task_groups_path %>

app/views/task_groups/index.html.erb
<h1>Listing task_groups</h1>

<table>
  <tr>
    <th>Task</th>
    <th>User</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_groups.each do |task_group| %>
  <tr>
    <td><%= task_group.task_id %></td>
    <td><%= task_group.user_id %></td>
    <td><%= task_group.role_id %></td>
    <td><%= link_to 'Show', task_group %></td>
    <td><%= link_to 'Edit', edit_task_group_path(task_group) %></td>
    <td><%= link_to 'Destroy', task_group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task group', new_task_group_path %>

app/views/task_groups/new.html.erb
<h1>New task_group</h1>

<%= render 'form' %>

<%= link_to 'Back', task_groups_path %>

app/views/task_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @task_group.task_id %>
</p>

<p>
  <b>User:</b>
  <%= @task_group.user_id %>
</p>

<p>
  <b>Role:</b>
  <%= @task_group.role_id %>
</p>


<%= link_to 'Edit', edit_task_group_path(@task_group) %> |
<%= link_to 'Back', task_groups_path %>